### SQL-Script zum Daten Einfügen im KichtenBuddyDB ###

USE kitchenbuddy;


### Erstmal ein große menge (250) an zustaten die amhaufigsten benuzt sind

INSERT INTO Zutaten (Zutat, Ingredient, Lebensmittelgruppe, Season)
VALUES
    ('Aubergine', 'Eggplant', 'Gemüse', 'Sommer'),
    ('Zucchini', 'Zucchini', 'Gemüse', 'Sommer'),
    ('Fenchel', 'Fennel', 'Gemüse', 'Herbst'),
    ('Rote Bete', 'Beetroot', 'Gemüse', 'Herbst'),
    ('Spargel', 'Asparagus', 'Gemüse', 'Frühling'),
    ('Kürbis', 'Pumpkin', 'Gemüse', 'Herbst'),
    ('Chinakohl', 'Chinese Cabbage', 'Gemüse', 'Winter'),
    ('Rotkohl', 'Red Cabbage', 'Gemüse', 'Winter'),
    ('Grünkohl', 'Kale', 'Gemüse', 'Winter'),
    ('Blumenkohl', 'Cauliflower', 'Gemüse', 'Herbst'),
    ('Mangold', 'Swiss Chard', 'Gemüse', 'Frühling'),
    ('Süßkartoffel', 'Sweet Potato', 'Gemüse', 'Herbst'),
    ('Okra', 'Okra', 'Gemüse', 'Sommer'),
    ('Bohnenkeimlinge', 'Bean Sprouts', 'Gemüse', 'Ganzjährig'),
    ('Artischocke', 'Artichoke', 'Gemüse', 'Frühling'),
    ('Rucola', 'Arugula', 'Gemüse', 'Frühling'),
    ('Endivie', 'Endive', 'Gemüse', 'Herbst'),
    ('Radieschen', 'Radish', 'Gemüse', 'Frühling'),
    ('Romanesco', 'Romanesco', 'Gemüse', 'Herbst'),
    ('Schalotte', 'Shallot', 'Gemüse', 'Ganzjährig'),
    ('Apfel', 'Apple', 'Frucht', 'Herbst'),
    ('Birne', 'Pear', 'Frucht', 'Herbst'),
    ('Banane', 'Banana', 'Frucht', 'Ganzjährig'),
    ('Orange', 'Orange', 'Frucht', 'Winter'),
    ('Mango', 'Mango', 'Frucht', 'Sommer'),
    ('Erdbeere', 'Strawberry', 'Frucht', 'Frühling'),
    ('Blaubeere', 'Blueberry', 'Frucht', 'Sommer'),
    ('Trauben', 'Grapes', 'Frucht', 'Herbst'),
    ('Himbeere', 'Raspberry', 'Frucht', 'Sommer'),
    ('Kirsche', 'Cherry', 'Frucht', 'Sommer'),
    ('Zitrone', 'Lemon', 'Frucht', 'Ganzjährig'),
    ('Limette', 'Lime', 'Frucht', 'Ganzjährig'),
    ('Pfirsich', 'Peach', 'Frucht', 'Sommer'),
    ('Nektarine', 'Nectarine', 'Frucht', 'Sommer'),
    ('Melone', 'Melon', 'Frucht', 'Sommer'),
    ('Wassermelone', 'Watermelon', 'Frucht', 'Sommer'),
    ('Ananas', 'Pineapple', 'Frucht', 'Sommer'),
    ('Kiwi', 'Kiwi', 'Frucht', 'Winter'),
    ('Granatapfel', 'Pomegranate', 'Frucht', 'Winter'),
    ('Feige', 'Fig', 'Frucht', 'Herbst'),
    ('Dattel', 'Date', 'Frucht', 'Winter'),
    ('Pflaume', 'Plum', 'Frucht', 'Herbst'),
    ('Aprikose', 'Apricot', 'Frucht', 'Sommer'),
    ('Johannisbeere', 'Currant', 'Frucht', 'Sommer'),
    ('Stachelbeere', 'Gooseberry', 'Frucht', 'Sommer'),
    ('Quark', 'Quark', 'Milchprodukt', 'Ganzjährig'),
    ('Joghurt', 'Yogurt', 'Milchprodukt', 'Ganzjährig'),
    ('Milch', 'Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Kondensmilch', 'Condensed Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Butter', 'Butter', 'Milchprodukt', 'Ganzjährig'),
    ('Käse', 'Cheese', 'Milchprodukt', 'Ganzjährig'),
    ('Mozzarella', 'Mozzarella', 'Milchprodukt', 'Ganzjährig'),
    ('Parmesan', 'Parmesan', 'Milchprodukt', 'Ganzjährig'),
    ('Ricotta', 'Ricotta', 'Milchprodukt', 'Ganzjährig'),
    ('Feta', 'Feta', 'Milchprodukt', 'Ganzjährig'),
    ('Schmand', NULL, 'Milchprodukt', 'Ganzjährig'),
    ('Mascarpone', 'Mascarpone', 'Milchprodukt', 'Ganzjährig'),
    ('Hüttenkäse', 'Cottage Cheese', 'Milchprodukt', 'Ganzjährig'),
    ('Camembert', 'Camembert', 'Milchprodukt', 'Ganzjährig'),
    ('Tofu', 'Tofu', 'Protein', 'Ganzjährig'),
    ('Tempeh', 'Tempeh', 'Protein', 'Ganzjährig'),
    ('Seitan', 'Seitan', 'Protein', 'Ganzjährig'),
    ('Eier', 'Eggs', 'Protein', 'Ganzjährig'),
    ('Hühnchen', 'Chicken', 'Fleisch', 'Ganzjährig'),
    ('Pute', 'Turkey', 'Fleisch', 'Ganzjährig'),
    ('Rindfleisch', 'Beef', 'Fleisch', 'Ganzjährig'),
    ('Schweinefleisch', 'Pork', 'Fleisch', 'Ganzjährig'),
    ('Lamm', 'Lamb', 'Fleisch', 'Ganzjährig'),
    ('Wurst', 'Sausage', 'Fleisch', 'Ganzjährig'),
    ('Speck', 'Bacon', 'Fleisch', 'Ganzjährig'),
    ('Hackfleisch', 'Ground Meat', 'Fleisch', 'Ganzjährig'),
    ('Leber', 'Liver', 'Fleisch', 'Ganzjährig'),
    ('Fisch', 'Fish', 'Fisch', 'Ganzjährig'),
    ('Lachs', 'Salmon', 'Fisch', 'Ganzjährig'),
    ('Thunfisch', 'Tuna', 'Fisch', 'Ganzjährig'),
    ('Forelle', 'Trout', 'Fisch', 'Ganzjährig'),
    ('Makrele', 'Mackerel', 'Fisch', 'Ganzjährig'),
    ('Sardinen', 'Sardines', 'Fisch', 'Ganzjährig'),
    ('Shrimps', 'Shrimps', 'Fisch', 'Ganzjährig'),
    ('Garnelen', 'Prawns', 'Fisch', 'Ganzjährig'),
    ('Muscheln', 'Mussels', 'Fisch', 'Ganzjährig'),
    ('Tintenfisch', 'Squid', 'Fisch', 'Ganzjährig'),
    ('Krabben', 'Crab', 'Fisch', 'Ganzjährig'),
    ('Hummer', 'Lobster', 'Fisch', 'Ganzjährig'),
    ('Reis', 'Rice', 'Getreide', 'Ganzjährig'),
    ('Nudeln', 'Pasta', 'Getreide', 'Ganzjährig'),
    ('Brot', 'Bread', 'Getreide', 'Ganzjährig'),
    ('Haferflocken', 'Oatmeal', 'Getreide', 'Ganzjährig'),
    ('Couscous', 'Couscous', 'Getreide', 'Ganzjährig'),
    ('Bulgur', 'Bulgur', 'Getreide', 'Ganzjährig'),
    ('Quinoa', 'Quinoa', 'Getreide', 'Ganzjährig'),
    ('Mais', 'Corn', 'Getreide', 'Sommer'),
    ('Gerste', 'Barley', 'Getreide', 'Ganzjährig'),
    ('Hirse', 'Millet', 'Getreide', 'Ganzjährig'),
    ('Weizen', 'Wheat', 'Getreide', 'Ganzjährig'),
    ('Roggen', 'Rye', 'Getreide', 'Ganzjährig'),
    ('Dinkel', 'Spelt', 'Getreide', 'Ganzjährig'),
    ('Mehl', 'Flour', 'Getreide', 'Ganzjährig'),
    ('Paniermehl', 'Breadcrumbs', 'Getreide', 'Ganzjährig'),
    ('Zucker', 'Sugar', 'Süßungsmittel', 'Ganzjährig'),
    ('Honig', 'Honey', 'Süßungsmittel', 'Ganzjährig'),
    ('Ahornsirup', 'Maple Syrup', 'Süßungsmittel', 'Ganzjährig'),
    ('Agavendicksaft', 'Agave Syrup', 'Süßungsmittel', 'Ganzjährig'),
    ('Stevia', 'Stevia', 'Süßungsmittel', 'Ganzjährig'),
    ('Salz', 'Salt', 'Gewürz', 'Ganzjährig'),
    ('Pfeffer', 'Pepper', 'Gewürz', 'Ganzjährig'),
    ('Paprikapulver', 'Paprika powder', 'Gewürz', 'Ganzjährig'),
    ('Chili', 'Chili', 'Gewürz', 'Ganzjährig'),
    ('Muskatnuss', 'Nutmeg', 'Gewürz', 'Ganzjährig'),
    ('Zimt', 'Cinnamon', 'Gewürz', 'Ganzjährig'),
    ('Kurkuma', 'Turmeric', 'Gewürz', 'Ganzjährig'),
    ('Ingwer', 'Ginger', 'Gewürz', 'Ganzjährig'),
    ('Knoblauchpulver', 'Garlic Powder', 'Gewürz', 'Ganzjährig'),
    ('Zwiebelpulver', 'Onion Powder', 'Gewürz', 'Ganzjährig'),
    ('Kreuzkümmel', 'Cumin', 'Gewürz', 'Ganzjährig'),
    ('Koriander', 'Coriander', 'Gewürz', 'Ganzjährig'),
    ('Senf', 'Mustard', 'Gewürz', 'Ganzjährig'),
    ('Sojasauce', 'Soy Sauce', 'Würze', 'Ganzjährig'),
    ('Fischsauce', 'Fish Sauce', 'Würze', 'Ganzjährig'),
    ('Worcestersauce', 'Worcestershire Sauce', 'Würze', 'Ganzjährig'),
    ('Essig', 'Vinegar', 'Würze', 'Ganzjährig'),
    ('Balsamico', 'Balsamic Vinegar', 'Würze', 'Ganzjährig'),
    ('Öl', 'Oil', 'Fett', 'Ganzjährig'),
    ('Olivenöl', 'Olive Oil', 'Fett', 'Ganzjährig'),
    ('Rapsöl', 'Canola Oil', 'Fett', 'Ganzjährig'),
    ('Sonnenblumenöl', 'Sunflower Oil', 'Fett', 'Ganzjährig'),
    ('Kokosöl', 'Coconut Oil', 'Fett', 'Ganzjährig'),
    ('Sesamöl', 'Sesame Oil', 'Fett', 'Ganzjährig'),
    ('Butterfett', 'Clarified Butter', 'Fett', 'Ganzjährig'),
    ('Margarine', 'Margarine', 'Fett', 'Ganzjährig'),
    ('Schokolade', 'Chocolate', 'Süßigkeit', 'Ganzjährig'),
    ('Kakaopulver', 'Cocoa Powder', 'Süßigkeit', 'Ganzjährig'),
    ('Backpulver', 'Baking Powder', 'Backzutat', 'Ganzjährig'),
    ('Natron', 'Baking Soda', 'Backzutat', 'Ganzjährig'),
    ('Vanillezucker', 'Vanilla Sugar', 'Backzutat', 'Ganzjährig'),
    ('Vanilleschote', 'Vanilla Bean', 'Backzutat', 'Ganzjährig'),
    ('Hefe', 'Yeast', 'Backzutat', 'Ganzjährig'),
    ('Gelatine', 'Gelatin', 'Bindemittel', 'Ganzjährig'),
    ('Agar-Agar', 'Agar Agar', 'Bindemittel', 'Ganzjährig'),
    ('Maisstärke', 'Cornstarch', 'Bindemittel', 'Ganzjährig'),
    ('Puddingpulver', 'Pudding Mix', 'Süßigkeit', 'Ganzjährig'),
    ('Rosinen', 'Raisins', 'Trockenfrucht', 'Ganzjährig'),
    ('Cranberries', 'Cranberries', 'Trockenfrucht', 'Ganzjährig'),
    ('Aprikosen (getrocknet)', 'Dried Apricots', 'Trockenfrucht', 'Ganzjährig'),
    ('Datteln (getrocknet)', 'Dried Dates', 'Trockenfrucht', 'Ganzjährig'),
    ('Feigen (getrocknet)', 'Dried Figs', 'Trockenfrucht', 'Ganzjährig'),
    ('Kokosraspeln', 'Desiccated Coconut', 'Trockenfrucht', 'Ganzjährig'),
    ('Mandeln', 'Almonds', 'Nüsse', 'Ganzjährig'),
    ('Haselnüsse', 'Hazelnuts', 'Nüsse', 'Ganzjährig'),
    ('Walnüsse', 'Walnuts', 'Nüsse', 'Ganzjährig'),
    ('Cashews', 'Cashews', 'Nüsse', 'Ganzjährig'),
    ('Pekanüsse', 'Pecans', 'Nüsse', 'Ganzjährig'),
    ('Paranüsse', 'Brazil Nuts', 'Nüsse', 'Ganzjährig'),
    ('Macadamianüsse', 'Macadamia Nuts', 'Nüsse', 'Ganzjährig'),
    ('Pinienkerne', 'Pine Nuts', 'Nüsse', 'Ganzjährig'),
    ('Sonnenblumenkerne', 'Sunflower Seeds', 'Samen', 'Ganzjährig'),
    ('Kürbiskerne', 'Pumpkin Seeds', 'Samen', 'Herbst'),
    ('Chiasamen', 'Chia Seeds', 'Samen', 'Ganzjährig'),
    ('Leinsamen', 'Flaxseeds', 'Samen', 'Ganzjährig'),
    ('Sesam', 'Sesame', 'Samen', 'Ganzjährig'),
    ('Mohn', 'Poppy Seeds', 'Samen', 'Ganzjährig'),
    ('Tahini', 'Tahini', 'Paste', 'Ganzjährig'),
    ('Ketchup', 'Ketchup', 'Würze', 'Ganzjährig'),
    ('Mayonnaise', 'Mayonnaise', 'Würze', 'Ganzjährig'),
    ('Senf (scharf)', 'Hot Mustard', 'Würze', 'Ganzjährig'),
    ('Barbecuesauce', 'Barbecue Sauce', 'Würze', 'Sommer'),
    ('Pesto', 'Pesto', 'Würze', 'Sommer'),
    ('Tomatenmark', 'Tomato Paste', 'Würze', 'Ganzjährig'),
    ('Sahne', 'Cream', 'Milchprodukt', 'Ganzjährig'),
    ('Kokosmilch', 'Coconut Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Sojamilch', 'Soy Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Hafermilch', 'Oat Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Mandelmilch', 'Almond Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Reismilch', 'Rice Milk', 'Milchprodukt', 'Ganzjährig'),
    ('Eis', 'Ice Cream', 'Süßigkeit', 'Sommer'),
    ('Griechischer Joghurt', 'Greek Yogurt', 'Milchprodukt', 'Ganzjährig'),
    ('Frischkäse', 'Cream Cheese', 'Milchprodukt', 'Ganzjährig'),
    ('Sauerrahm', 'Sour Cream', 'Milchprodukt', 'Ganzjährig'),
    ('Buttermilch', 'Buttermilk', 'Milchprodukt', 'Ganzjährig'),
    ('Erdnussbutter', 'Peanut Butter', 'Aufstrich', 'Ganzjährig'),
    ('Haselnusscreme', 'Hazelnut Spread', 'Aufstrich', 'Ganzjährig'),
    ('Marmelade', 'Jam', 'Aufstrich', 'Ganzjährig'),
    ('Konfitüre', 'Preserve', 'Aufstrich', 'Ganzjährig'),
    ('Apfelmus', 'Applesauce', 'Frucht', 'Herbst'),
    ('Pflaumenmus', 'Plum Jam', 'Frucht', 'Herbst'),
    ('Fruchtkompott', 'Fruit Compote', 'Frucht', 'Ganzjährig'),
    ('Kandierte Früchte', 'Candied Fruits', 'Frucht', 'Winter'),
    ('Zitronensaft', 'Lemon Juice', 'Würze', 'Ganzjährig'),
    ('Limettensaft', 'Lime Juice', 'Würze', 'Sommer'),
    ('Orangensaft', 'Orange Juice', 'Frucht', 'Winter'),
    ('Apfelsaft', 'Apple Juice', 'Frucht', 'Herbst'),
    ('Traubensaft', 'Grape Juice', 'Frucht', 'Herbst'),
    ('Brühe', 'Broth', 'Flüssigkeit', 'Ganzjährig'),
    ('Gemüsebrühe', 'Vegetable Broth', 'Flüssigkeit', 'Ganzjährig'),
    ('Hühnerbrühe', 'Chicken Broth', 'Flüssigkeit', 'Ganzjährig'),
    ('Rinderbrühe', 'Beef Broth', 'Flüssigkeit', 'Ganzjährig'),
    ('Fischfond', 'Fish Stock', 'Flüssigkeit', 'Ganzjährig'),
    ('Weißwein', 'White Wine', 'Flüssigkeit', 'Ganzjährig'),
    ('Rotwein', 'Red Wine', 'Flüssigkeit', 'Ganzjährig'),
    ('Apfelessig', 'Apple Cider Vinegar', 'Würze', 'Ganzjährig'),
    ('Weißweinessig', 'White Wine Vinegar', 'Würze', 'Ganzjährig'),
    ('Reisessig', 'Rice Vinegar', 'Würze', 'Ganzjährig'),
    ('Mirin', 'Mirin', 'Würze', 'Ganzjährig'),
    ('Sherry', 'Sherry', 'Flüssigkeit', 'Ganzjährig'),
    ('Portwein', 'Port Wine', 'Flüssigkeit', 'Ganzjährig'),
    ('Rumaroma', 'Rum Flavoring', 'Aroma', 'Ganzjährig'),
    ('Vanilleextrakt', 'Vanilla Extract', 'Aroma', 'Ganzjährig'),
    ('Mandelaroma', 'Almond Extract', 'Aroma', 'Ganzjährig'),
    ('Orangenabrieb', 'Orange Zest', 'Frucht', 'Winter'),
    ('Zitronenabrieb', 'Lemon Zest', 'Frucht', 'Sommer'),
    ('Lorbeerblätter', 'Bay Leaves', 'Gewürz', 'Ganzjährig'),
    ('Wacholderbeeren', 'Juniper Berries', 'Gewürz', 'Ganzjährig'),
    ('Nelken', 'Cloves', 'Gewürz', 'Winter'),
    ('Sternanis', 'Star Anise', 'Gewürz', 'Winter'),
    ('Kardamom', 'Cardamom', 'Gewürz', 'Winter'),
    ('Fenchelsamen', 'Fennel Seeds', 'Gewürz', 'Ganzjährig'),
    ('Anis', 'Anise', 'Gewürz', 'Ganzjährig'),
    ('Bockshornklee', 'Fenugreek', 'Gewürz', 'Ganzjährig'),
    ('Currypulver', 'Curry Powder', 'Gewürz', 'Ganzjährig'),
    ('Garam Masala', 'Garam Masala', 'Gewürz', 'Ganzjährig'),
    ('Fünf-Gewürze-Pulver', 'Five Spice Powder', 'Gewürz', 'Ganzjährig'),
    ('Chiliflocken', 'Chili Flakes', 'Gewürz', 'Ganzjährig'),
    ('Basilikum', 'Basil', 'Kräuter', 'Sommer'),
    ('Petersilie', 'Parsley', 'Kräuter', 'Ganzjährig'),
    ('Schnittlauch', 'Chives', 'Kräuter', 'Ganzjährig'),
    ('Dill', 'Dill', 'Kräuter', 'Sommer'),
    ('Thymian', 'Thyme', 'Kräuter', 'Ganzjährig'),
    ('Rosmarin', 'Rosemary', 'Kräuter', 'Ganzjährig'),
    ('Oregano', 'Oregano', 'Kräuter', 'Ganzjährig'),
    ('Minze', 'Mint', 'Kräuter', 'Sommer'),
    ('Estragon', 'Tarragon', 'Kräuter', 'Sommer'),
    ('Lorbeer', 'Bay Leaf', 'Kräuter', 'Ganzjährig'),
    ('Salbei', 'Sage', 'Kräuter', 'Ganzjährig'),
    ('Bohnenkraut', 'Savory', 'Kräuter', 'Sommer'),
    ('Majoran', 'Marjoram', 'Kräuter', 'Sommer'),
    ('Zitronenmelisse', 'Lemon Balm', 'Kräuter', 'Sommer'),
    ('Knoblauch', 'Garlic', 'Gemüse', 'Ganzjährig'),
    ('Zwiebel', 'Onion', 'Gemüse', 'Ganzjährig'),
    ('Lauch', 'Leek', 'Gemüse', 'Winter'),
    ('Karotte', 'Carrot', 'Gemüse', 'Ganzjährig'),
    ('Sellerie', 'Celery', 'Gemüse', 'Ganzjährig'),
    ('Pastinake', 'Parsnip', 'Gemüse', 'Winter'),
    ('Thunfisch Steak', 'Tuna Steak' , 'Fisch', 'Ganzjährig'),
    ('Currypaste', 'Currypaste', 'Gewürz', 'Ganzjährig'),
    ('Tomaten', 'Tomato', 'Gemüse', 'Ganzjährig'),
    ('Salatmix', 'Salad mix', 'Gemüse', 'Ganzjährig'),
    ('Paprika', 'Capsicum', 'Gemüse', 'Ganzjährig'),
    ('Kräuter', 'Herbs', 'Kräuter', 'Ganzjährig'),
    ('Lasagneplatten', 'Lasagne sheets', 'Getreide', NULL),
    ('Majorann', 'Majorann', 'Kräuter', NULL),
    ('Kartoffeln', 'Potato', 'Gemüse', NULL),
    ('Linsen', 'Linsen', 'Legume', NULL),
    ('Sushireis', 'Sushireis', 'Getreide', NULL),
    ('Nori-Blätter', 'Nori', 'Seaweed', NULL),
    ('Avocado', 'Avocado', 'Gemüse', 'Winter'),
    ('Gurke', 'Cucumber', 'Gemuse', NULL),
    ('Wasabi', 'Wasabi', 'Würze', NULL),
    ('Mürbeteig', 'Shortcrust pastry', 'Teig', NULL);




INSERT INTO einkaufstyp (Typ, Kostenranking, Beschreibung)
VALUES
    ('Lebensmittelladen', 1, 'Einfache Lebenesmittlegeschäft wie; Edeka, REVE, ALDI, etc...'),
    ('BIOmarkt', 3, 'BIOläden wie; Biocompany, LPG, Denns'),
    ('Backieri', 2, 'Alle von frisch brot und semmeln'),
    ('Asienladen', 2, 'Spezielle lädan für Asienprodukte'),
    ('Metzger', 4, 'Wo man frisch und höher quality fleisch kauft, aber kostet naturlich mehr'),
    ('Käseladen', 4, 'KÄSE!!'),
    ('Delikatessen', 3, 'Spezielle laden für cold-cut, Deli'),
    ('Ganz Spezielleläden', 5, 'wie bei Kaviar, trüffeln, etc... muss man entwieder online oder zum spezifischladen gehen'),
    ('arabischer supermarkt', 1, 'arabischer supermarkt gut für lamm, gewürze, andrean sachen'),
    ('Fischhändler', 4, 'Wo man frisch Meersfruchten kauft');


## prozeduren dass setzt die ~250 amhaufigsten benutzt zutaten bei normal und biomarkten typen
CALL InsertAmhaufigstenEinkaufstypfür1und2();


## den Reste zutant bei spezifischer läden zu ordnen
INSERT INTO einkaufen (ZutatID, EinkaufstypID)
VALUE
    (13, 4), (13, 9),
    (68, 4), (68, 9),
    (72, 4), (72, 7), (72, 8),
    (73, 10),
    (74, 10),
    (75, 10),
    (76, 10),
    (77, 10),
    (78, 10),
    (79, 10), (79, 4),
    (80, 10), (80, 4),
    (81, 10), (81, 4),
    (82, 10), (82, 4),
    (83, 10), (83, 8),
    (84, 10), (84, 8),
    (85, 4),
    (87, 3),
    (118, 4),
    (119, 4),
    (197, 10), (197, 8),
    (203, 4),
    (243, 10), (243, 8),
    (244, 4), (244, 9),
    (253, 4),
    (254, 4),
    (257, 4);


#### Eingeben von mealarten
INSERT INTO mealarten (Mealart, Beschreibung)
VALUES
        ('Vegan', 'Gerichte ohne tierische Produkte, ausschließlich pflanzlich.'),
        ('Vegetarisch', 'Gerichte ohne Fleisch und Fisch, oft mit Milchprodukten oder Eiern.'),
        ('Meal Prep', 'Vorgekochte Mahlzeiten zur Aufbewahrung und späterem Verzehr.'),
        ('Desserts / Süßspeisen', 'Süße Speisen, meist als Abschluss einer Mahlzeit serviert.'),
        ('Comfort Food', 'Hausgemachte, oft nostalgische Gerichte mit hohem Wohlfühlfaktor.');



### Erste 10 rezepte eingeben
INSERT INTO rezepte(Titel, Kueche, Schwerigkeit, Zeit, Methode)
VALUES
    ('Spaghetti aglio e olio', 'Italienisch', 1, 1,
     'Spaghetti nach Packungsanweisung in Salzwasser al dente kochen. In einer Pfanne Olivenöl erhitzen, fein gehackten Knoblauch und Chiliflocken darin leicht anrösten. Nudeln abgießen, etwas Kochwasser aufheben. Nudeln mit dem Öl vermengen, mit Petersilie und Kochwasser abschmecken, servieren.'),

     ('Kartoffelsuppe', 'Deutsch', 2, 2,
      'Roast potats - Peel the potatoes and pass through a ricer. \n Bacon on onion and garlic, Add milk, season with salt and pepper to taste. Bring to a boil over high heat, reduce to a gentle simmer and cook until flavors meld, about 10 minutes, \nUsing an immersion blender, purée onion, garlic, and milk until smooth. Add riced potatoes and sour cream, stirring to combine, until soup is warmed through.'),

     ('Gemüse-Curry mit Reis', 'Indisch', 2, 3,
      'Reis nach Packungsanleitung kochen. In einer großen Pfanne Zwiebeln, Knoblauch und Ingwer anbraten. Gewürfeltes Gemüse wie Zucchini, Karotten und Paprika zugeben. Currypaste einrühren, mit Kokosmilch und etwas Wasser aufgießen. Etwa 20 Minuten köcheln lassen. Mit Limettensaft und Koriander servieren.'),

     ('Shakshuka', 'Orientalisch', 2, 2,
      'Zwiebeln und Knoblauch in Olivenöl anschwitzen. Gewürfelte Paprika zugeben und mitbraten. Tomaten (frisch oder aus der Dose) zufügen, würzen mit Kreuzkümmel, Paprika, Salz und Pfeffer. Etwa 10 Minuten einkochen lassen. Mulden formen, Eier hineinschlagen, zugedeckt stocken lassen. Mit Brot servieren.'),

     ('Bunter Salat mit Hähnchen', 'International', 1, 1,
      'Hähnchenbrustfilets würzen und in einer Pfanne durchbraten, anschließend in Scheiben schneiden. Salat (z. B. Rucola, Feldsalat), Paprika, Tomaten und Gurken waschen und schneiden. Alles in einer großen Schüssel anrichten. Ein Dressing aus Olivenöl, Balsamico, Senf und Honig zubereiten und darübergeben.'),

     ('Basic Lasagne', 'Italienisch', 4, 4,
      'Zwiebeln und Knoblauch anbraten, Hackfleisch zugeben und krümelig braten. Tomatenmark und gehackte Tomaten einrühren, würzen und 20 Min. köcheln lassen. Für die Béchamel Butter schmelzen, Mehl einrühren, Milch unter Rühren zugeben und aufkochen. In einer Auflaufform Hacksoße, Béchamel und Lasagneplatten schichten, mit Käse bestreuen. Bei 180°C ca. 40 Min. backen.'),

     ('Gulasch', 'Ungarisch', 3, 4,
      'Rindfleisch in Würfel schneiden. Zwiebeln in Butterschmalz goldbraun rösten. Fleisch zugeben und kräftig anbraten. Mit Paprikapulver, Salz, Pfeffer und Majoran würzen. Mit Brühe aufgießen und zugedeckt bei niedriger Hitze ca. 2–3 Stunden schmoren lassen. Bei Bedarf etwas Flüssigkeit nachgießen.'),

     ('Veganer Linseneintopf', 'Vegan', 2, 3,
      'Zwiebeln und Knoblauch anbraten, gewürfelte Möhren, Sellerie und Kartoffeln zugeben. Linsen waschen und mit in den Topf geben. Mit Gemüsebrühe aufgießen und ca. 30–40 Minuten köcheln lassen. Mit Essig, Salz, Pfeffer und Kräutern abschmecken. Nach Wunsch mit frischem Brot servieren.'),

     ('Sushi-Rollen', 'Japanisch', 5, 5,
      'Sushireis gründlich waschen, nach Packungsanleitung garen und mit Reisessig, Zucker und Salz würzen. Abkühlen lassen. Noriblätter auf einer Bambusmatte auslegen, mit Reis gleichmäßig bedecken, Wunschfüllung (z. B. Avocado, Gurke, Lachs) darauf verteilen. Eng einrollen, mit scharfem Messer schneiden, mit Sojasoße servieren.'),

     ('Quiche Lorraine', 'Französisch', 4, 3,
      'Mürbeteig zubereiten oder fertig verwenden, in eine gefettete Form drücken. Speck und Zwiebeln anbraten, auf dem Teig verteilen. Eier, Sahne, Salz, Pfeffer und Muskat verquirlen, über die Füllung gießen. Mit geriebenem Käse bestreuen. Im vorgeheizten Ofen bei 180°C ca. 40 Minuten goldbraun backen.');


### Erste 10 rezepte zutat beziehung eingeben
INSERT INTO rezept_zutaten (RezeptID, ZutatID, Menge)
VALUES
    (1, 86, '200g'), (1, 237,'6 Stück, fein gehackt'), (1, 124, '4 EL'), (1, 222, '1/2 TL'), (1, 224, '1 EL, frisch gehackt (optional)'),
    (2, 70, '(12 ounces; 340g), diced'), (2, 238, '1 big boy'), (2, 237, 'viel :)'), (2, 251, '1.1kg'), (2, 48, '1L'), (2, 178, '1 cup plus some for serving'), (2, 225, 'CHIVE PLZ'),
    (3, 85, '150 g'), (3, 238, '1 Stück, gewürfelt'), (3, 237, '2 Stück, fein gehackt'), (3, 112, '1 TL, frisch gerieben'), (3, 2, '1 kleine, gewürfelt'),
    (3, 240, '2 Stück, in Scheiben'), (3, 107, '1 Stück, gewürfelt'), (3, 244, '2 EL (rot oder gelb)'), (3, 170, '400 ml'), (3, 126, '2 EL'), (3, 189, '1 EL'), (3, 116, 'einige Blätter, zum Garnieren'),
    (4, 238, '1 Stück, gewürfelt'), (4, 237, '2 Stück, fein gehackt'), (4, 247, '1 Stück, gewürfelt'), (4, 245, '400 g, aus der Dose oder frisch'), (4, 63, '3–4 Stück'), (4, 124, '2 EL'),
    (4, 107, '1 TL'), (4, 115, '1/2 TL'), (4, 224, 'frisch gehackt, zum Garnieren'), (4, 87, 'nach Bedarf, zum Servieren'),
    (5, 64, '250 g'), (5, 246, '100 g'), (5, 245, '2 Stück, gewürfelt'), (5, 247, '1 Stück, in Streifen'), (5, 124, '2 EL'), (5, 122, '1 EL'), (5, 101, '1 TL'), (5, 117, '1 TL'), (5, 248, 'frisch, gehackt'),
    (6, 71, '400 g'), (6, 238, '1 Stück, fein gewürfelt'), (6, 237, '2 Stück, fein gehackt'), (6, 168, '2 EL'), (6, 245, 'Dose 400 g'), (6, 249, '250 g'), (6, 50, '50 g'),
    (6, 98, '50 g'), (6, 48, '500 ml'), (6, 52, '150 g'), (6, 124, '2 EL'), (6, 109, 'frisch gerieben, nach Geschmack'),
    (7, 66, '600 g, in Würfel geschnitten'),  (7, 238, '2 Stück, grob gewürfelt'), (7, 50, '3 EL'), (7, 107, '2 EL'), (7, 250, '1 TL'), (7, 196, '500 ml'), (7, 237, '1 Stück, fein gehackt'), (7, 211, '1 Stück'),
    (8, 238, '1 Stück, gewürfelt'), (8, 237, '2 Stück, fein gehackt'), (8, 240, '2 Stück, gewürfelt'), (8, 241, '2 Stangen, gewürfelt'), (8, 251, '300 g, gewürfelt'), (8, 252, '200 g'), (8, 194, '1 Liter'), (8, 201, '1 EL'), (8, 224, 'frisch, gehackt'),
    (9, 253, '250 g'), (9, 202, '3 EL'), (9, 100, '1 EL'), (9, 254, '5 Stück'), (9, 255, '1 Stück, in Streifen'), (9, 256, '1/2 Stück, in Streifen'), (9, 73, '150 g'), (9, 118, 'zum Servieren'), (9, 257, 'nach Geschmack'), (9, 112, 'zum Servieren'),
    (10, 258, '1 Rolle (fertig) oder selbstgemacht aus 200 g Mehl, 100 g Butter, 1 Ei'), (10, 70, '150 g'), (10, 238, '1 Stück, fein gewürfelt'), (10, 63, '3 Stück'), (10, 169, '200 ml'), (10, 48, '50 ml'), (10, 51, '100 g Gerieben'), (10, 109, 'nach Geschmack');



###Beziehung zwischen die 10 erste rezepte und meal arten einflügen
INSERT INTO rezeptarten (RezeptID, MealartID)
VALUES
    (1, 2),
    (2, 2), (2, 3),
    (3, 1), (3, 3),
    (4, 2),
    (6, 3), (6, 5),
    (7, 3),
    (8, 1), (8, 3),
    (9, 5);

